/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/v1/connect/oauth2/authorize": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Authorization Code
     * @description This endpoint is used when the end user must approve access to a protected resource (such as a cart) before a service can act on the user's behalf. Here's how it works:
     *
     *     * Your service or application calls this endpoint and includes the redirect URL (what the end user should see after this service executes) and scopes (defines the actions your application or service can take on behalf of the user).
     *     * This endpoint displays a login screen, where the end user enters their email address and password.
     *     * The end user is then asked to give the application permission to access the resource on their behalf.
     *     * When the user agrees, this service returns the redirect URL with an authorization `code` as a parameter.
     *
     *     After this endpoint returns, your service or application must call the `/token` endpoint with the `authorization_code` grant type and `code` value to get an access token. The access token is then sent to the endpoint being called to prove that your service or application is authorized to act on a user's behalf.
     *
     */
    get: operations["authorizationCode"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/connect/oauth2/token": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Access Token
     * @description All Oauth2 applications are issued "client credentials" in the form of a unique client_id and client_secret after registration. The credentials are used to authorize the application.
     *     <br/><br/>
     *     There are 3 grant type flows that the token endpoint offers:
     *     1. `authorization_code` - Uses the `code` returned from the `/authorize` endpoint to get a token, allowing your service or application to make API requests on an end user's behalf, including accessing personal data. The service is only able to perform the actions specified in the approved scopes.
     *     2. `client_credentials` - Uses the client credentials to provide a token that allows your service or application to call endpoints that do not require user approval.
     *     3. `refresh_token`	- Allows the application to "refresh" an access token that has expired. Refresh tokens are only granted when using the Authorization Code grant type. Using the refresh token eliminates the need to re-authenticate the customer when the access token expires.
     *
     *     The `access_token` received from this step is sent to the endpoint being called to prove that your service or application is authorized to call the API. The `token_type` field indicates what type of token it is so that you can correctly pass it to the API.
     *
     */
    post: operations["accessToken"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    auth_server_error: {
      errors?: {
        /**
         * @description Description of the reason for the error
         * @example Internal server error
         */
        reason?: string;
        /**
         * @description Unique identifier for the error used for troubleshooting purposes
         * @example Auth-4xxx-xxx
         */
        code?: string;
        /**
         * @description Timestamp of the resposne
         * @example 1564159296910
         */
        timestamp?: number;
      };
    };
    authorization_code: {
      /**
       * @description Must be `authorization_code`. (enum property replaced by openapi-typescript)
       * @enum {string}
       */
      grant_type: "authorization_code";
      /**
       * @description The value of the `code` parameter returned from the `/authorization` endpoint on the redirect URL.
       * @example zWrT1GkdshSadIowJW0Rm4w2kKhOzv1W
       */
      code: string;
      /**
       * @description Your registered redirect URL. Must be the same redirect URL that was used for the authorizations code request.
       * @example https://example.com/callback
       */
      redirect_uri: string;
    };
    authorization_code_response: {
      /**
       * @description How long the access token is valid for in seconds.
       * @example 1800
       */
      expires_in?: number;
      /**
       * @description The access token string
       * @example eyJh5GciOiJSUzI1NiGsImtpZCI6Ilo0RnQzbXNrSUj4OGlydDdMQjVjNmc2PSIsInR5cCI6IkpXVmJ9.eqJzY29wZSI6InByb2T1Y3QuY29tcGFjdCBjb3Vwb24uYmFzaWMiLCJhdXRoQXQiOjE1NjUwOTk0OTUzMzIzOTIxMTIsImF1ZCI6InBlcmsvcm1hbmNlLWFnZW50LXB1YmxpYyIsImV4cCI6MTU2NTEwMTI5NSwiaWF0IjoxNTY1MDk5BDkwLCJpc3MiOiJhcGkua3JvZ2VyLmNvbSIsInN1YiI6IjBmZjdkMGIwLWVkOGItNDJmOS1hNTExLWEzMGQyYTAyZDljNSJ9.ej0mov6SGV4n4HiAvduTdYCceMlSo3T06M4Nfh3MfpIjSKzKaLWgd5S0W1EKDXrWz8IE7NTg8EIrL-WKhwdZPt-TWaS7LLjRXLJ0w5rKc44DStgBdvDiCcnKeMsnimjhBlHOiiKUV5y3GbVqJzaDVZwg0j8lP9qtwZP9EIIQ7k409nkskY1pz7l1lZrGotYRJKmnteN5vVQeZ3R8jywIwOOSEbKSgQALVA3Oj02964P7lI6h1GsZ66V5FLA9KU8QXm4ejrFHf1beAIA2zi_fQI3dmW7yj57pWoCECZIjq7Sfo3nGR5rkjEwfyXEK7aTn8oj4_14YHgKRTY-28L96cw
       */
      access_token?: string;
      /**
       * @description The type of token.
       * @example bearer
       */
      token_type?: string;
      /**
       * @description A token that can be used to request a new token on behalf of the end user. Refresh tokens have a longer expiration, typically 24 hours.
       * @example FN20LbaF2EWC6MPMWdemBwwnP4ZmX8
       */
      refresh_token?: string;
    };
    client_credentials: {
      /**
       * @description Must be `client_credentials`. (enum property replaced by openapi-typescript)
       * @enum {string}
       */
      grant_type: "client_credentials";
      /**
       * @description The level of access your application is requesting. Available options can be found on your app page.
       * @example product.compact
       */
      scope?: string;
    };
    client_credentials_response: {
      /**
       * @description How long the access token is valid for in seconds.
       * @example 1800
       */
      expires_in?: number;
      /**
       * @description The access token string.
       * @example eyJh5GciOiJSUzI1NiGsImtpZCI6Ilo0RnQzbXNrSUj4OGlydDdMQjVjNmc2PSIsInR5cCI6IkpXVmJ9.eqJzY29wZSI6InByb2T1Y3QuY29tcGFjdCBjb3Vwb24uYmFzaWMiLCJhdXRoQXQiOjE1NjUwOTk0OTUzMzIzOTIxMTIsImF1ZCI6InBlcmsvcm1hbmNlLWFnZW50LXB1YmxpYyIsImV4cCI6MTU2NTEwMTI5NSwiaWF0IjoxNTY1MDk5BDkwLCJpc3MiOiJhcGkua3JvZ2VyLmNvbSIsInN1YiI6IjBmZjdkMGIwLWVkOGItNDJmOS1hNTExLWEzMGQyYTAyZDljNSJ9.ej0mov6SGV4n4HiAvduTdYCceMlSo3T06M4Nfh3MfpIjSKzKaLWgd5S0W1EKDXrWz8IE7NTg8EIrL-WKhwdZPt-TWaS7LLjRXLJ0w5rKc44DStgBdvDiCcnKeMsnimjhBlHOiiKUV5y3GbVqJzaDVZwg0j8lP9qtwZP9EIIQ7k409nkskY1pz7l1lZrGotYRJKmnteN5vVQeZ3R8jywIwOOSEbKSgQALVA3Oj02964P7lI6h1GsZ66V5FLA9KU8QXm4ejrFHf1beAIA2zi_fQI3dmW7yj57pWoCECZIjq7Sfo3nGR5rkjEwfyXEK7aTn8oj4_14YHgKRTY-28L96cw
       */
      access_token?: string;
      /**
       * @description The type of token.
       * @example bearer
       */
      token_type?: string;
    };
    invalid_access: {
      /**
       * @description The error message
       * @example invalid_request
       */
      error?: string;
      /**
       * @description Detailed error description
       * @example The resource owner denied the request
       */
      error_description?: string;
    };
    invalid_code: {
      /**
       * @description The error message
       * @example invalid_request
       */
      error?: string;
      /**
       * @description Detailed error description
       * @example invalid code
       */
      error_description?: string;
    };
    invalid_credentials: {
      /**
       * @description The error message
       * @example unauthorized
       */
      error?: string;
      /**
       * @description Detailed error description
       * @example invalid credentials
       */
      error_description?: string;
    };
    invalid_grant_type: {
      /**
       * @description The error message
       * @example unsupported_grant_type
       */
      error?: string;
      /**
       * @description Detailed error description
       * @example invalid grant_type
       */
      error_description?: string;
    };
    invalid_redirect_uri: {
      /**
       * @description The error message
       * @example invalid_request
       */
      error?: string;
      /**
       * @description Detailed error description
       * @example The redirect_uri did not match the registered redirect_uri for this application
       */
      error_description?: string;
    };
    invalid_refresh_token: {
      /**
       * @description The error message
       * @example invalid_request
       */
      error?: string;
      /**
       * @description Detailed error description
       * @example invalid refresh_token
       */
      error_description?: string;
    };
    invalid_scope: {
      /**
       * @description The error message
       * @example invalid_scope
       */
      error?: string;
      /**
       * @description Detailed error description
       * @example invalid scope
       */
      error_description?: string;
    };
    /**
     * @description Your registered redirect with the authorization code appended to the URL.
     * @example https://YourRedirectUri.com/callback?code=zWrT1GkdshSadIowJW0Rm4w2kKhOzv1W
     */
    oauth2_code_response: string;
    refresh_token: {
      /**
       * @description Must be `refresh_token`. (enum property replaced by openapi-typescript)
       * @enum {string}
       */
      grant_type: "refresh_token";
      /**
       * @description The refresh token returned from a call to this endpoint with the `authorization_code` or `refresh_token` grant type.
       * @example FN20LbaF2EWC6MPMWdemBwwnP4ZmX8
       */
      refresh_token: string;
    };
    refresh_token_response: {
      /**
       * @description How long the access token is valid for in seconds.
       * @example 1800
       */
      expires_in?: number;
      /**
       * @description The access token string.
       * @example eyJh5GciOiJSUzI1NiGsImtpZCI6Ilo0RnQzbXNrSUj4OGlydDdMQjVjNmc2PSIsInR5cCI6IkpXVmJ9.eqJzY29wZSI6InByb2T1Y3QuY29tcGFjdCBjb3Vwb24uYmFzaWMiLCJhdXRoQXQiOjE1NjUwOTk0OTUzMzIzOTIxMTIsImF1ZCI6InBlcmsvcm1hbmNlLWFnZW50LXB1YmxpYyIsImV4cCI6MTU2NTEwMTI5NSwiaWF0IjoxNTY1MDk5BDkwLCJpc3MiOiJhcGkua3JvZ2VyLmNvbSIsInN1YiI6IjBmZjdkMGIwLWVkOGItNDJmOS1hNTExLWEzMGQyYTAyZDljNSJ9.ej0mov6SGV4n4HiAvduTdYCceMlSo3T06M4Nfh3MfpIjSKzKaLWgd5S0W1EKDXrWz8IE7NTg8EIrL-WKhwdZPt-TWaS7LLjRXLJ0w5rKc44DStgBdvDiCcnKeMsnimjhBlHOiiKUV5y3GbVqJzaDVZwg0j8lP9qtwZP9EIIQ7k409nkskY1pz7l1lZrGotYRJKmnteN5vVQeZ3R8jywIwOOSEbKSgQALVA3Oj02964P7lI6h1GsZ66V5FLA9KU8QXm4ejrFHf1beAIA2zi_fQI3dmW7yj57pWoCECZIjq7Sfo3nGR5rkjEwfyXEK7aTn8oj4_14YHgKRTY-28L96cw
       */
      access_token?: string;
      /**
       * @description The type of token.
       * @example bearer
       */
      token_type?: string;
      /**
       * @description A token that can be used to request a new token on behalf of the end user. Refresh tokens have a longer expiration, typically 24 hours.
       * @example FN20LbaF2EWC6MPMWdemBwwnP4ZmX8
       */
      refresh_token?: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  authorizationCode: {
    parameters: {
      query: {
        /** @description The level of access your application is requesting. */
        scope: string;
        /** @description Your application's client ID. */
        client_id: string;
        /** @description Your registered redirect URL. The redirect URL tells this endpoint which URL to display after the user approves access to the protected resource. */
        redirect_uri: string;
        /** @description Is always `code`. */
        response_type: string;
        /** @description A random string to verify that the response belongs to the initiated request. The server should always return the same state value as the one specified in the request to protect against forgery attacks. */
        state?: string;
        /** @description Sets the chain specific branding displayed on the authorization consent screen presented to the end user for shopper logins. When this parameter is not supplied the default chain branding (Kroger) will be used. Only one option may be used at a time and the available options are the following:
         *
         *     "bakers" - Bakers' Plus
         *     "citymarket" - City Market
         *     "dillons" - Dillons
         *     "fredmeyer" - Fred Meyer
         *     "frys" - Fry's Food
         *     "gerbes" - Gerbes
         *     "kingsoopers" - King Soopers
         *     "kroger" - Kroger (default if no banner provided)
         *     "metromarket" - Metro Market
         *     "picknsave" - Pick 'n Save
         *     "qfc" - QFC
         *     "ralphs" - Ralphs
         *     "smiths" - Smiths Food and Drug
         *     "food4less" - Food 4 Less"
         *     "foodsco" - Foods Co.
         *     "harristeeter" - Harris Teeter
         *     "vons" - Vons
         *     "fredmeyerjewelers" - Fred Meyer
         *     "jaycfoods" - Jay C
         *     "marianos" - Marianos
         *     "payless" - Pay Less
         *     "ppsrx" - Postal Prescription Services (PPSRX)
         *     "rulerfoods" - Ruler Foods
         *     "copps" - Copps
         *      */
        banner?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Moved Permanently */
      301: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["oauth2_code_response"];
        };
      };
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json":
            | components["schemas"]["invalid_scope"]
            | components["schemas"]["invalid_grant_type"]
            | components["schemas"]["invalid_redirect_uri"]
            | components["schemas"]["invalid_access"]
            | components["schemas"]["invalid_credentials"];
        };
      };
      /** @description Internal Server Error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["auth_server_error"];
        };
      };
    };
  };
  accessToken: {
    parameters: {
      query?: never;
      header: {
        /** @description Your `client_id:client_secret` base64 encoded. */
        Authorization: string;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: {
      content: {
        "application/x-www-form-urlencoded":
          | components["schemas"]["authorization_code"]
          | components["schemas"]["client_credentials"]
          | components["schemas"]["refresh_token"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json":
            | components["schemas"]["authorization_code_response"]
            | components["schemas"]["client_credentials_response"]
            | components["schemas"]["refresh_token_response"];
        };
      };
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json":
            | components["schemas"]["invalid_code"]
            | components["schemas"]["invalid_scope"]
            | components["schemas"]["invalid_grant_type"]
            | components["schemas"]["invalid_refresh_token"]
            | components["schemas"]["invalid_credentials"];
        };
      };
      /** @description Internal Server Error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["auth_server_error"];
        };
      };
    };
  };
}
