/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/v1/cart/add": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /**
     * Add to cart
     * @description Provides access to add items to an authenticated customer's cart.
     *     <br><br> **Note**: the customer must be authenticated using the
     *     OAuth2 Authorization Code grant type.
     *
     */
    put: operations["putCarts"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    APIError: {
      timestamp?: number;
      code?: string;
      reason?: string;
    };
    "APIError.cart.serverError": {
      errors?: {
        /** @example Internal server error */
        reason?: string;
        /** @example CART-4xxx-xxx */
        code?: string;
        /** @example 1564159296910 */
        timestamp?: number;
      };
    };
    "APIError.forbidden": {
      errors?: {
        /** @example missing required scopes */
        reason?: string;
        /** @example Forbidden */
        code?: string;
        /** @example 1564143270221 */
        timestamp?: number;
      };
    };
    "APIError.unauthorized": {
      errors?: {
        /** @example The access token is invalid or has expired */
        error_description?: string;
        /** @example invalid_token */
        error?: string;
      };
    };
    "cart.cartItemModel": {
      /**
       * @description The quantity of the item.
       * @example 1
       */
      quantity: number;
      /**
       * @description The `UPC` of the item.
       * @example 0001111060903
       */
      upc: string;
      /**
       * @description An optional value representing a modality including: DELIVERY, PICKUP.
       * @default PICKUP
       * @enum {string}
       */
      modality: "DELIVERY" | "PICKUP";
    };
    "cart.cartItemRequestModel": {
      /** @description An array of items in the cart. */
      items?: components["schemas"]["cart.cartItemModel"][];
    };
    "Invalid.modality": {
      /** @example 1569851999383 */
      timestamp?: number;
      /** @example API-4101-400 */
      code?: string;
      /** @example Modality must be omitted or equal one of the following codes: DELIVERY, PICKUP */
      reason?: string;
    };
    "Invalid.parameters": {
      /** @example 1569851999383 */
      timestamp?: number;
      /** @example API-4101-400 */
      code?: string;
      /** @example Cannot parse parameters */
      reason?: string;
    };
    "Invalid.UPC": {
      /** @example 1569851999383 */
      timestamp?: number;
      /** @example API-4101-400 */
      code?: string;
      /** @example UPC must have a length of 13 characters */
      reason?: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  putCarts: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description A list of items that you are adding to the cart. */
    requestBody?: {
      content: {
        "application/json": components["schemas"]["cart.cartItemRequestModel"];
      };
    };
    responses: {
      /** @description OK */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json":
            | components["schemas"]["APIError"]
            | components["schemas"]["Invalid.UPC"]
            | components["schemas"]["Invalid.modality"]
            | components["schemas"]["Invalid.parameters"];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["APIError.unauthorized"];
        };
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["APIError.forbidden"];
        };
      };
      /** @description Internal Server Error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["APIError.cart.serverError"];
        };
      };
    };
  };
}
