/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/catalog/v2/products": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Catalog Search
     * @description Search the product catalog based upon specified criteria.
     */
    get: {
      parameters: {
        query: {
          /**
           * @description Exact match to product identifier, typically UPC, or GTIN.
           *
           *     Duplicate UPCs if present in the request parameter are ignored.
           *
           *     Max allowed non-duplicate UPCs per request: 50
           */
          "filter.upc.in"?: string;
          /**
           * @description Exact match to the 8-character locationId for the store or distribution center.
           *
           *     (filter.storeId.eq in the original Catalog Search endpoint.)
           */
          "filter.locations.id.eq": string;
          /**
           * @description Exact match to product fulfillment option.
           *
           *     Must be one of: DELIVERY, SHIP, PICKUP, or INSTORE.
           *
           *     (filter.modality.eq in the original Catalog Search endpoint.)
           */
          "filter.locations.fulfillment.eq": string;
          /**
           * @description Exact match to postal code or ZIP code. (When filter.modality is set to DELIVERY for Ocado stores.)
           *
           *     **This is a required field to request Ocado DELIVERY store products.**
           *
           *     **Note:** For US addresses, one can use either the 5-digit or 9-digit ZIP+4.
           */
          "filter.postalCode.eq"?: string;
          /**
           * @description The updated date range provided as a comma separated set with the start date and end date in that order.
           *
           *     Products updated within this range (inclusive) will be returned.
           */
          "filter.updatedAt.range"?: string;
          /**
           * @description Controls whether items without pricing information are included in the response.
           *
           *     - If omitted or set to `false`, only items with pricing information available will be returned.
           *     - If set to `true`, all items will be included. Items without pricing details will also appear in the API response.
           *
           *     **Note:** Use this parameter when you want to include UPCs that don't have any associated pricing data.
           */
          "option.missingPrices"?: boolean;
          /**
           * @description Starting point for paginated results.
           * @example 50
           */
          "page.offset"?: components["parameters"]["catalog_v2_page.offset"];
          /**
           * @description Number of products obtained per page.<br><br>Allowed range: [1 - 50]
           * @example 25
           */
          "page.size"?: components["parameters"]["catalog_v2_page.size"];
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Success */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["catalog_v2.products.response"];
          };
        };
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["catalog_v2.clientError.400"];
          };
        };
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["catalog_v2.serverError.500"];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/catalog/v2/products-inventory": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Catalog Inventory
     * @description Search a location's product catalog for inventory-specific details. Current stock levels, fulfillment status, and active promotions are included.
     */
    get: {
      parameters: {
        query: {
          /** @description Exact match to product identifier, typically UPC, or GTIN.<br><br>Duplicate UPCs if present in the request parameter are ignored. <br><br>Max allowed non-duplicate UPCs per request: 50 */
          "filter.upc.in"?: string;
          /**
           * @description Exact match to the 8-character locationId for the store or distribution center.
           *
           *     (filter.storeId.eq in the original Catalog Search endpoint.)
           */
          "filter.locations.id.eq": string;
          /**
           * @description Exact match to product fulfillment option.<br><br>Must be one of: DELIVERY, SHIP, PICKUP, or INSTORE.
           *
           *     (filter.modality.eq in the original Catalog Search endpoint.)
           */
          "filter.locations.fulfillment.eq": string;
          /** @description The last stock level updated date range provided as a comma separated set with the start date and end date in that order. Products with stock levels updated within this range (inclusive) will be returned. */
          "filter.stockLevelUpdatedAt.range"?: string;
          /** @description The last fulfillment updated date range provided as a comma separated set with the start date and end date in that order. Products with fulfillment updated within this range (inclusive) will be returned. */
          "filter.fulfillmentUpdatedAt.range"?: string;
          /** @description The updated date range provided as a comma separated set with the start date and end date in that order. Products updated within this range (inclusive) will be returned. */
          "filter.updatedAt.range"?: string;
          /**
           * @description Exact match to postal code or ZIP code. (When filter.modality is set to DELIVERY for Ocado stores.)
           *
           *     **This is a required field to request Ocado DELIVERY store products.**
           *
           *     **Note:** For US addresses, one can use either the 5-digit or 9-digit ZIP+4.
           */
          "filter.postalCode.eq"?: string;
          /**
           * @description Controls whether items without pricing information are included in the response.
           *
           *     - If omitted or set to `false`, only items with pricing information available will be returned.
           *     - If set to `true`, all items will be included. Items without pricing details will still appear, with their `prices` field set to an empty array `[]`.
           *
           *     **Note:** Use this parameter when you want to include UPCs that don't have any associated pricing data.
           */
          "option.missingPrices"?: boolean;
          /**
           * @description Starting point for paginated results.
           * @example 50
           */
          "page.offset"?: components["parameters"]["catalog_v2_page.offset"];
          /**
           * @description Number of products obtained per page.<br><br>Allowed range: [1 - 50]
           * @example 25
           */
          "page.size"?: components["parameters"]["catalog_v2_page.size"];
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Success */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["catalog_v2.products-inventory.response"];
          };
        };
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["catalog_v2.clientError.400"];
          };
        };
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["catalog_v2.serverError.500"];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/catalog/v2/deleted-items": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Disabled Items
     * @description Returns the disabled items based upon specified criteria.
     */
    get: {
      parameters: {
        query: {
          /**
           * @description Exact match to the 8-character locationId for the store or distribution center.
           *
           *     (filter.storeId.eq in the original Catalog Search endpoint.)
           */
          "filter.locations.id.eq": string;
          /**
           * @description Exact match to product fulfillment option.
           *
           *     Must be one of: DELIVERY, SHIP, PICKUP, or INSTORE.
           *
           *     (filter.modality.eq in the original Catalog Search endpoint.)
           */
          "filter.locations.fulfillment.eq": string;
          /**
           * @description The deleted date range provided as a comma separated set with the start date and end date in that order.
           *
           *     Products disabled within this range (inclusive) will be returned.
           *
           *     Note: The maximum supported range for this parameter is 2 days.
           */
          "filter.deletedAt.range": string;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Success */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["catalog_v2.deleted-items.response"];
          };
        };
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["catalog_v2.clientError.400"];
          };
        };
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["catalog_v2.serverError.500"];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    "catalog_v2.products-inventory.response": {
      data?: components["schemas"]["catalog_v2.products-inventory.data"];
      meta?: components["schemas"]["catalog_v2.products.meta"];
    };
    "catalog_v2.products.response": {
      data?: components["schemas"]["catalog_v2.products.data"];
      meta?: components["schemas"]["catalog_v2.products.meta"];
    };
    "catalog_v2.products-inventory.data": components["schemas"]["catalog_v2.products-inventory"][];
    "catalog_v2.products.data": components["schemas"]["catalog_v2.products"][];
    "catalog_v2.products": {
      /**
       * @description Product identifier, usually an UPC/GTIN.
       * @example 0081801301354
       */
      upc?: string;
      /**
       * @description An array of alternate UPCs or GTINs associated with the product.
       * @example [
       *       "00812396017148",
       *       "00882645000955",
       *       "00033074301018",
       *       "00705123040932",
       *       "00851339002179"
       *     ]
       */
      aliasUPCs?: string[];
      /**
       * @description Product name.
       * @example Simple Truth™ Paso Robles Cabernet Sauvignon
       */
      name?: string;
      /**
       * @description Product description.
       * @example Our organic Cabernet Sauvignon grapes are grown on one of California's largest organic vineyards, in the hills of Paso Robles on the Central Coast. With its wide day-to-night temperature swings and fossil-rich marine limestones, this growing region provides unique stressors that produce deep, intense flavors with structure and elegance.
       */
      description?: string;
      /** @description Product last updated timestamp. */
      updatedAt?: {
        /**
         * Format: date-time
         * @example 2020-04-17T08:11:34.021Z
         */
        value?: string;
        /** @example UTC */
        timezone?: string;
      };
      /**
       * @description Product Description Page URL.
       * @example https://www.kroger.com/p/reed-s-original-real-ginger-ale-4-cans/0000827466500?cid=dis.api.tpi_catalog-api_20250501_b:all_c:p_t:3t0yu6vjv8
       */
      productPageURL?: string;
      brand?: components["schemas"]["catalog_v2.products.brand"];
      categories?: components["schemas"]["catalog_v2.products.categories"];
      metadata?: components["schemas"]["catalog_v2.products.metadata"];
      /** @description Product images. */
      images?: components["schemas"]["catalog_v2.image"];
      /**
       * @description A brief description of the item as displayed on the receipt.
       * @example MCDONALDS VL GC
       */
      receiptDescription?: string;
    };
    "catalog_v2.deleted-items.response": {
      data?: string[];
    };
    "catalog_v2.products-inventory": {
      /**
       * @description Product identifier, usually an UPC/GTIN.
       * @example 0081801301354
       */
      upc?: string;
      /**
       * @description Product name.
       * @example Simple Truth™ Paso Robles Cabernet Sauvignon
       */
      name?: string;
      locations?: components["schemas"]["catalog_v2.products.locations"];
      /** @description Product stocklevel last updated timestamp. */
      stockLevelUpdatedAt?: {
        /**
         * Format: date-time
         * @example 2020-04-17T08:11:34.021Z
         */
        value?: string;
        /** @example UTC */
        timezone?: string;
      };
      /** @description Product fulfillment last updated timestamp. */
      fulfillmentUpdatedAt?: {
        /**
         * Format: date-time
         * @example 2020-04-17T08:11:34.021Z
         */
        value?: string;
        /** @example UTC */
        timezone?: string;
      };
      /** @description Product price last updated timestamp. */
      priceUpdatedAt?: {
        /**
         * Format: date-time
         * @example 2020-04-17T08:11:34.021Z
         */
        value?: string;
        /** @example UTC */
        timezone?: string;
      };
      /** @description Product stock or stocklevel or fulfillment last updated timestamp. */
      updatedAt?: {
        /**
         * Format: date-time
         * @example 2020-04-17T08:11:34.021Z
         */
        value?: string;
        /** @example UTC */
        timezone?: string;
      };
      /** @description Prices based on postal codes */
      postalCodes?: {
        /**
         * @description Postal code
         * @example 75201
         */
        postalCode?: string;
        /** @description List of prices available for this postal code */
        prices?: {
          /**
           * @description Complex Promo language (tags) from upstream - Support for store-level pricing indicators.
           * @example YellowTag
           */
          discountLabel?: string;
          /**
           * @description Previous reference price amount for PriceDrop/PriceCut promotions.
           * @example USD 2.69
           */
          referencePriceAmt?: string;
          /**
           * @description Previous N-for quantity for PriceDrop/PriceCut promotions.
           * @example 4
           */
          referenceNForCnt?: number;
          /**
           * @description Sold by unit or weight
           * @example UNIT
           */
          soldBy?: string;
          /** @description Regular price information */
          regular?: {
            /**
             * @description Default price description
             * @example $4.99
             */
            defaultDescription?: string;
            /** @description Number of items for the given price */
            nFor?: {
              /**
               * @description Price
               * @example USD 4.99
               */
              price?: string;
              /**
               * @description Quantity
               * @example 1
               */
              quantity?: number;
            };
            /**
             * @description Price
             * @example USD 4.99
             */
            price?: string;
          };
          /** @description Promo price information. */
          promo?: {
            /**
             * @description Human-readable promo price description.
             * @example $3.99
             */
            defaultDescription?: string;
            /** @description Number of items for the given price */
            nFor?: {
              /**
               * @description Price
               * @example USD 3.99
               */
              price?: string;
              /**
               * @description Quantity
               * @example 1
               */
              quantity?: number;
            };
            /**
             * @description Price
             * @example USD 3.99
             */
            price?: string;
            /**
             * Format: date-time
             * @description Start date and time when the promo price is effective.
             * @example 2024-08-09T00:00:00Z
             */
            effectiveDate?: string;
            /**
             * Format: date-time
             * @description Date and time when the promo price expires.
             * @example 2024-08-16T23:59:59Z
             */
            expiredDate?: string;
          };
        }[];
      }[];
    };
    /** @description Product brand */
    "catalog_v2.products.brand": {
      /**
       * @description Brand name.
       * @example Simple Truth
       */
      name?: string;
      metadata?: components["schemas"]["catalog_v2.products.brand.metadata"];
    };
    "catalog_v2.products.brand.metadata": {
      /**
       * @description Kroger's marketing brand name.
       * @example Simple Truth
       */
      marketingName?: string;
    };
    "catalog_v2.products.category": {
      parent?: {
        department?: {
          /**
           * @description Department name.
           * @example Natural & Organic
           */
          name?: string;
          /**
           * @description Department code
           * @example 18
           */
          code?: string;
        };
        commodity?: {
          /**
           * @description Commodity name.
           * @example Grocery
           */
          name?: string;
          /**
           * @description Commodity code
           * @example 012
           */
          code?: string;
        };
        subCommodity?: {
          /**
           * @description Sub commodity name.
           * @example Bars
           */
          name?: string;
          /**
           * @description Sub commodity code
           * @example 00014
           */
          code?: string;
        };
      };
    };
    /** @description Product locations. */
    "catalog_v2.products.locations": {
      /**
       * @description Unique identifier for Kroger store or distribution center location.
       * @example 70100485
       */
      id?: string;
      aisleLocations?: components["schemas"]["catalog_v2.products.locations.aisleLocations"];
      inventory?: components["schemas"]["catalog_v2.products.locations.inventory"];
      fulfillment?: components["schemas"]["catalog_v2.products.locations.fulfillment"];
      restriction?: components["schemas"]["catalog_v2.products.locations.restriction"];
    }[];
    /** @description Order quantity restrictions for the location. */
    "catalog_v2.products.locations.restriction": {
      /**
       * @description Maximum order quantity.
       * @example 4
       */
      maxOrderQuantity?: number;
    };
    "catalog_v2.products.metadata": {
      package?: components["schemas"]["catalog_v2.products.metadata.package"];
      /**
       * @description Product quantity.
       * @example 1 lb
       */
      size?: string;
      /**
       * @description Product gtin14.
       * @example 00052100071039
       */
      gtin14?: string;
      /** @description Product nutritional preferences. */
      nutritionalPreferences?: ("GLUTEN_FREE" | "LIVE_NATURALLY" | "ORGANIC" | "NON_GMO")[];
      /**
       * @description Product's country of origin
       * @example UNITED STATES
       */
      countryOfOrigin?: string;
      temperature?: components["schemas"]["catalog_v2.products.metadata.temperature"];
      /**
       * @description Indicates if an item is eligible for Supplemental Nutrition Assistance Program (SNAP) or not.
       * @example true
       */
      snapEligible?: boolean;
      /**
       * @description Indicates if an item is alcoholic
       * @example true
       */
      alcoholic?: boolean;
      /**
       * @description Identifies the alcohol proof of the product.
       * @example 84
       */
      alcoholProof?: number;
      /**
       * @description Indicates if an item has any restriction or not
       * @example true
       */
      restrictedItem?: boolean;
      /**
       * @description Indicates if an item has age restriction
       * @example true
       */
      ageRestrictionFlag?: boolean;
      /**
       * @description Average weight per unit of the product ( This field is calculated when the Order by is unit and the Sell by is weight ).
       * @example 0.3 [lb_av]
       */
      averageWeightPerUnit?: string;
    };
    /** @description Temparature information of a product */
    "catalog_v2.products.metadata.temperature": {
      /**
       * @description Indicates if an item is heat sensitive or not
       * @example true
       */
      heatSensitive?: boolean;
      /**
       * @description Temparature indicator of a product
       * @example Refrigerated
       */
      indicator?: string;
    };
    /** @description Package details like dimensions and weight. */
    "catalog_v2.products.metadata.package": {
      /**
       * @description Product length.
       * @example 3.55 [in_i]
       */
      length?: string;
      /**
       * @description Product width.
       * @example 8.85 [in_i]
       */
      width?: string;
      /**
       * @description Product height.
       * @example 13.4 [in_i]
       */
      height?: string;
      /**
       * @description Product shape.
       * @example Cylindrical
       */
      shape?: string;
      /**
       * @description Product weight.
       * @example 4.2 [lb_av]
       */
      weight?: string;
    };
    "catalog_v2.products.meta": {
      page?: components["schemas"]["catalog_v2.products.meta.page"];
    };
    "catalog_v2.image": {
      /** @enum {string} */
      perspective?: "FRONT" | "BACK" | "LEFT" | "RIGHT";
      /** @example true */
      default?: boolean;
      sizes?: components["schemas"]["catalog_v2.image.resolution.sizes"][];
    }[];
    "catalog_v2.image.resolution.sizes": {
      /** @example http://www.example.com/image.jpg */
      url?: string;
      /** @example medium */
      descriptor?: string;
    };
    /** @description Product inventory */
    "catalog_v2.products.locations.inventory": {
      stock?: components["schemas"]["catalog_v2.products.locations.inventory.stock"];
      /**
       * @description Indicates if a product is instock at a store location or not.
       * @example true
       */
      instock?: boolean;
      prices?: components["schemas"]["catalog_v2.products.locations.inventory.prices"];
    }[];
    "catalog_v2.products.locations.inventory.stock": {
      /**
       * @description Number of products instock.
       * @example 4
       */
      availableToSell?: number;
      /**
       * @description Level of stock of particular product.
       * @example HIGH
       */
      level?: string;
    };
    "catalog_v2.products.locations.inventory.prices.price.nFor": {
      /**
       * @description Number of product units
       * @example 4
       */
      quantity?: string;
      /**
       * @description Product price if given quantity is bought.
       * @example USD 18.00
       */
      price?: string;
    };
    /** @description Product aisleLocations in a given store location. */
    "catalog_v2.products.locations.aisleLocations": {
      /**
       * @description Product aisle.
       * @example aisle
       */
      aisle?: string;
      aisleDescription?: string;
      aisleSide?: string;
      /**
       * @description Product shelf.
       * @example shelf
       */
      shelf?: string;
      /**
       * @description Product position.
       * @example position
       */
      position?: string;
      bayNumber?: string;
      numberOfFacings?: string;
      /**
       * @description A 2-character string representing the department where the item is located.
       * @example GR
       */
      departmentCode?: string;
      /**
       * @description A long-form string providing the full name of the department where the item is located.
       * @example Grocery
       */
      departmentDescription?: string;
      /**
       * @description A 3-character numeric ID representing the area where the item is placed.
       * @example 010
       */
      areaId?: string;
      /**
       * @description A 2-character code that defines the type of area where the item is stored or displayed.
       * @example AL
       */
      areaTypeCode?: string;
      /**
       * @description A long-form description of the area type.
       * @example Aisle
       */
      areaTypeDescription?: string;
      /**
       * @description A 2 or 3 character numeric ID representing the sub-area within an aisle or section.
       * @example 001
       */
      subAreaId?: string;
      /**
       * @description A 2-character code representing a subsection within the main area.
       * @example EC
       */
      subAreaTypeCode?: string;
      /**
       * @description A long-form description of the sub-area where the product is stored or displayed.
       * @example Endcap
       */
      subAreaTypeDescription?: string;
      /**
       * @description A code representing the side or orientation of the fixture where the item is placed
       * @example L
       */
      orientationCode?: string;
      /**
       * @description A human-readable description of the product’s orientation within the fixture.
       * @example Left
       */
      orientationDescription?: string;
      /**
       * @description A numeric string representing the identifier of the fixture (e.g., a shelf) within the bay where the item is located. It resembles the legacy shelfNumber field and helps pinpoint the exact placement of the product.
       * @example 4
       */
      fixtureNumber?: string;
      /**
       * @description An abbreviated code used to represent the fixture location concisely.
       * @example DRAL010EC001F006
       */
      fixLocAbbreviated?: string;
      /**
       * @description The type of location where the product is stored/displayed.
       * @example displayLocation
       */
      locationType?: string;
    }[];
    "catalog_v2.products.locations.inventory.prices": {
      /**
       * @description Complex Promo language (tags) from upstream - Support for store-level pricing indicators.
       * @example YellowTag
       */
      discountLabel?: string;
      /**
       * @description Previous reference price amount for PriceDrop/PriceCut promotions.
       * @example USD 2.69
       */
      referencePriceAmt?: string;
      /**
       * @description Previous N-for quantity for PriceDrop/PriceCut promotions.
       * @example 4
       */
      referenceNForCnt?: number;
      regular?: components["schemas"]["catalog_v2.products.locations.inventory.prices.price"];
      promo?: components["schemas"]["catalog_v2.products.locations.inventory.prices.price"];
    }[];
    /** @description Pricing details for the product. */
    "catalog_v2.products.locations.inventory.prices.price": {
      /**
       * @description Unit price of product
       * @example USD 5.00
       */
      unit?: string;
      /**
       * @description Product price description
       * @example Offer price
       */
      description?: string;
      /**
       * @description Default price description
       * @example $4.99
       */
      defaultDescription?: string;
      /**
       * @description Promo price description.
       * @example $19.88
       */
      promoDescription?: string;
      nFor?: components["schemas"]["catalog_v2.products.locations.inventory.prices.price.nFor"];
      /**
       * @description Sold by unit or weight.
       * @example UNIT
       * @enum {string}
       */
      soldBy?: "UNIT" | "WEIGHT";
      /** @description Product price type effective date. If there's a promo price, the effective date is associated with it; otherwise, it's associated with the regular price. */
      effectiveDate?: {
        /** @example 2020-04-09T14:23:41Z */
        value?: string;
        /** @example IST */
        timezone?: string;
      };
      /** @description Product price type expired date. If there's a promo price, the expiry date is associated with it; otherwise, it's associated with the regular price. */
      expiredDate?: {
        /** @example 2020-04-13T14:23:41Z */
        value?: string;
        /** @example IST */
        timezone?: string;
      };
    };
    /** @description Product fulfilment */
    "catalog_v2.products.locations.fulfillment": {
      /** @example true */
      delivery?: boolean;
      /** @example false */
      ship?: boolean;
      /** @example true */
      pickup?: boolean;
      /** @example false */
      instore?: boolean;
    };
    /** @description Product categories. */
    "catalog_v2.products.categories": components["schemas"]["catalog_v2.products.category"][];
    "catalog_v2.products.meta.page": {
      /**
       * @description Starting point for paginated results.
       * @example 0
       */
      offset?: number;
      /**
       * @description Number of products per page.
       * @example 20
       */
      size?: number;
      /** @description An optional flag to indicate if there are more products available beyond the current page to retrieve. */
      hasMore?: boolean;
    };
    "catalog_v2.clientError.400": {
      errors?: components["schemas"]["catalog_v2.APIError.clientError"];
    };
    "catalog_v2.APIError.clientError": {
      /** @example Invalid Parameter */
      code?: string;
      /** @example Incorrect value for parameter: locations.id */
      reason?: string;
      datetime?: {
        /** @example 2020-04-09T14:23:41Z */
        value?: string;
        /** @example IST */
        timezone?: string;
      };
    }[];
    "catalog_v2.serverError.500": {
      errors?: {
        /** @example Internal Server Error */
        code?: string;
        /** @example Sorry, an unexpected error has occurred. Please try again later. */
        reason?: string;
        datetime?: {
          /** @example 2020-04-09T14:23:41Z */
          value?: string;
          /** @example IST */
          timezone?: string;
        };
      }[];
    };
  };
  responses: never;
  parameters: {
    /**
     * @description Number of products obtained per page.<br><br>Allowed range: [1 - 50]
     * @example 25
     */
    "catalog_v2_page.size": number;
    /**
     * @description Starting point for paginated results.
     * @example 50
     */
    "catalog_v2_page.offset": number;
  };
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
