/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/v1/identity/profile": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * User profile information
     * @description Provides access to the profile `id` of an authenticated customer. <br><br> **Note**: the customer must be authenticated using the OAuth2 Authorization Code grant type.
     */
    get: operations["profileGet"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    "APIError.forbidden": {
      errors?: {
        /** @example missing required scopes */
        reason?: string;
        /** @example Forbidden */
        code?: string;
        /** @example 1564143270221 */
        timestamp?: number;
      };
    };
    "APIError.identity.serverError": {
      errors?: {
        /** @example Internal server error */
        reason?: string;
        /** @example IDENTITY-4xxx-xxx */
        code?: string;
        /** @example 1564159296910 */
        timestamp?: number;
      };
    };
    "APIError.unauthorized": {
      errors?: {
        /** @example The access token is invalid or has expired */
        error_description?: string;
        /** @example invalid_token */
        error?: string;
      };
    };
    "identity.profileModel": {
      data?: {
        /**
         * @description The customer's profile Id.
         * @example 53990804-cfd1-43f3-8256-bdc9817a4fd0
         */
        id?: string;
      };
      meta?: components["schemas"]["MetaModel"];
    };
    MetaModel: {
      pagination?: {
        total?: number;
        start?: number;
        limit?: number;
      };
      warnings?: string[];
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  profileGet: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["identity.profileModel"];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["APIError.unauthorized"];
        };
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["APIError.forbidden"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Internal Server Error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["APIError.identity.serverError"];
        };
      };
    };
  };
}
